M48
; DRILL file {KiCad (6.0.0)} date Wed Aug 31 12:15:51 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-31T12:15:51-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X115.703Y-57.869
X121.483Y-57.869
X169.068Y-57.844
X174.848Y-57.844
T0
M30
