function y = FilterWindowHammingFs1000Fc25_Order10(x)
%FILTERWINDOWHAMMINGFS1000FC25 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 21-Jul-2022 19:34:19

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Lowpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 1000;  % Sampling Frequency
    %
    % N    = 10;       % Order
    % Fc   = 25;       % Cutoff Frequency
    % flag = 'scale';  % Sampling Flag
    %
    % % Create the window vector for the design algorithm.
    % win = hamming(N+1);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.0133790352155543 0.0291679225936605 ...
        0.0711978808001632 0.124638058224915 0.168739779277884 0.185754647775644 ...
        0.168739779277884 0.124638058224915 0.0711978808001632 ...
        0.0291679225936605 0.0133790352155543]);
end

y = step(Hd,double(x));


% [EOF]
