function y = FilterWindowHammingFs1000Fc50_Order10(x)
%FILTERWINDOWHAMMINGFS1000FC50 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 21-Jul-2022 19:32:54

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Lowpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 1000;  % Sampling Frequency
    %
    % N    = 10;       % Order
    % Fc   = 50;       % Cutoff Frequency
    % flag = 'scale';  % Sampling Flag
    %
    % % Create the window vector for the design algorithm.
    % win = hamming(N+1);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.00996728268387249 0.0248616598269683 ...
        0.0668366890418819 0.124888939106605 0.175591860415964 0.195707137849416 ...
        0.175591860415964 0.124888939106605 0.0668366890418819 ...
        0.0248616598269683 0.00996728268387249]);
end

y = step(Hd,double(x));


% [EOF]
